import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Use — AI Video Platform",
  description: "Terms of Use for AI Video Platform iOS application.",
}

export default function TermsOfUse() {
  return (
    <main className="min-h-screen bg-white">
      <div className="mx-auto max-w-3xl px-6 py-24 md:py-32">
        <Link
          href="/"
          className="mb-12 inline-block text-sm text-text-secondary hover:text-text-primary transition-colors"
        >
          &larr; Back to home
        </Link>

        <h1 className="mb-4 text-4xl font-semibold tracking-apple-tight text-text-primary">
          Terms of Use
        </h1>
        <p className="mb-12 text-sm text-text-tertiary">
          Effective Date: May 10, 2026 &middot; Last Updated: May 10, 2026
        </p>

        <div className="prose-legal space-y-8 text-text-secondary [&_h2]:mb-4 [&_h2]:mt-12 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-text-primary [&_h3]:mb-2 [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-text-primary [&_p]:leading-relaxed [&_ul]:ml-4 [&_ul]:list-disc [&_ul]:space-y-1 [&_li]:leading-relaxed">

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              These Terms of Use (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and AI Video Platform (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) governing your access to and use of the AI Video Platform mobile application (the &ldquo;App&rdquo;) and associated website (collectively, the &ldquo;Services&rdquo;).
            </p>
            <p>
              BY DOWNLOADING, INSTALLING, ACCESSING, OR USING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT ACCESS OR USE THE SERVICES.
            </p>
            <p>
              The App is rated 17+ on the Apple App Store. By using the Services, you represent and warrant that you are at least 17 years of age. The Services are not available to users under the age of 17.
            </p>
          </section>

          <section>
            <h2>2. Account</h2>
            <p>
              When you first open the App, an anonymous account is automatically created for you via Firebase Authentication. You do not need to provide any personal information to use the Services.
            </p>
            <ul>
              <li>Each device creates one anonymous account. Accounts are tied to your device and are non-transferable.</li>
              <li>You are responsible for maintaining the security of your device and account.</li>
              <li>If you uninstall the App or reset your device, your anonymous account and associated data (including any remaining credits) may be permanently lost.</li>
              <li>We are not responsible for any loss of credits, content, or account access resulting from device changes, uninstallation, or data loss.</li>
            </ul>
          </section>

          <section>
            <h2>3. The Services</h2>
            <p>
              AI Video Platform provides AI-powered video generation and editing tools accessible through our iOS application. The Services allow you to:
            </p>
            <ul>
              <li>Generate video content from text prompts and/or uploaded images using third-party AI models</li>
              <li>Edit videos using AI-powered tools (style transfer, enhancement, captions)</li>
              <li>Export finished videos in various resolutions up to 4K</li>
            </ul>

            <h3>3.1 Third-Party AI Providers</h3>
            <p>
              Video generation is performed by the following third-party AI service providers:
            </p>
            <ul>
              <li><strong>OpenAI (Sora)</strong> &mdash; subject to <a href="https://openai.com/policies/terms-of-use" className="text-brand-500 hover:underline">OpenAI&rsquo;s Terms of Use</a></li>
              <li><strong>Google (Veo)</strong> &mdash; subject to <a href="https://policies.google.com/terms" className="text-brand-500 hover:underline">Google&rsquo;s Terms of Service</a></li>
              <li><strong>xAI (Grok)</strong> &mdash; subject to <a href="https://x.ai/legal/terms-of-service" className="text-brand-500 hover:underline">xAI&rsquo;s Terms of Service</a></li>
            </ul>
            <p>
              We act as an intermediary between you and these providers. Your use of our Services is also subject to each provider&rsquo;s terms. We do not control and are not responsible for the outputs generated by these third-party AI models, including their accuracy, quality, appropriateness, or legality.
            </p>

            <h3>3.2 Service Availability</h3>
            <p>
              We reserve the right to modify, suspend, or discontinue any aspect of the Services at any time, with or without notice, including the availability of specific AI providers. We shall not be liable to you or any third party for any modification, suspension, or discontinuance.
            </p>
            <p>
              The availability, quality, and speed of AI-generated content may vary due to third-party provider limitations, server capacity, or other factors beyond our control.
            </p>
          </section>

          <section>
            <h2>4. Credits, Subscriptions, and Payments</h2>

            <h3>4.1 Credit System</h3>
            <p>
              The Services operate on a credit-based system. Credits are required to generate videos and perform certain AI editing operations.
            </p>
            <ul>
              <li>The number of credits required per operation varies based on the type, duration, quality, and complexity of the requested output</li>
              <li>Credits have NO monetary value and cannot be redeemed for cash under any circumstances</li>
              <li>Credits are non-transferable between accounts or devices</li>
              <li>Credits are non-refundable except where required by applicable law</li>
              <li>We reserve the right to modify credit costs for operations at any time with or without notice</li>
              <li>If video generation fails due to a provider error, credits will be refunded to your account automatically</li>
            </ul>

            <h3>4.2 Subscriptions</h3>
            <p>
              Subscriptions are available on a weekly, monthly, or yearly basis and provide a recurring allocation of credits. By purchasing a subscription, you agree to the following:
            </p>
            <ul>
              <li>Payment will be charged to your Apple ID account at confirmation of purchase</li>
              <li>Subscriptions automatically renew unless canceled at least 24 hours before the end of the current billing period</li>
              <li>Your account will be charged for renewal within 24 hours prior to the end of the current period at the then-current rate</li>
              <li>Subscription credits are allocated at the beginning of each billing period</li>
              <li><strong>Unused subscription credits expire at the end of each billing period and do NOT roll over</strong></li>
              <li>No refunds or credits will be provided for unused portions of any billing period, including upon cancellation</li>
              <li>You may manage or cancel your subscription through iOS Settings &gt; [your name] &gt; Subscriptions</li>
              <li>Any unused portion of a free trial period (if offered) will be forfeited upon purchasing a subscription</li>
            </ul>

            <h3>4.3 One-Time Credit Purchases</h3>
            <p>
              You may purchase additional credits as one-time (non-recurring) In-App Purchases:
            </p>
            <ul>
              <li>One-time purchased credits do NOT expire</li>
              <li>Subscription credits are consumed before one-time purchased credits</li>
              <li>One-time purchased credits remain available even if you cancel your subscription</li>
              <li>One-time purchased credits are non-refundable except where required by applicable law</li>
              <li>One-time purchased credits are lost if you lose access to your anonymous account (e.g., by uninstalling the App)</li>
            </ul>

            <h3>4.4 Pricing Changes</h3>
            <p>
              We reserve the right to change subscription prices and credit pack prices at any time. Price changes for active subscriptions will take effect at the start of the next billing period following the date of the price change. Apple will notify you of price increases and require your consent before renewal at the new price.
            </p>

            <h3>4.5 Payment Processing</h3>
            <p>
              All payments are processed exclusively through Apple&rsquo;s In-App Purchase system, managed via Adapty. We do not process, store, or have access to your payment information. For payment disputes or refund requests, please contact Apple Support directly.
            </p>
          </section>

          <section>
            <h2>5. Intellectual Property</h2>

            <h3>5.1 Your Content</h3>
            <p>
              You retain ownership of the text prompts and images you submit to the Services (&ldquo;User Inputs&rdquo;). Subject to these Terms and the terms of the underlying AI providers, you may use the AI-generated video content produced from your User Inputs (&ldquo;Outputs&rdquo;) for personal and commercial purposes.
            </p>
            <p>
              You acknowledge and agree that:
            </p>
            <ul>
              <li>Due to the nature of AI technology, similar or substantially similar Outputs may be generated for other users who provide similar User Inputs. Your rights to Outputs are non-exclusive.</li>
              <li>We do not guarantee that Outputs will be unique, original, or non-infringing.</li>
              <li>Your rights to Outputs are subject to the terms and limitations of the third-party AI providers (OpenAI, Google, xAI) that generated them. You are responsible for reviewing and complying with their respective terms.</li>
              <li>You are solely responsible for ensuring that your use of Outputs complies with applicable laws and does not infringe the rights of any third party.</li>
            </ul>

            <h3>5.2 License to Us</h3>
            <p>
              By submitting User Inputs to the Services, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and transmit your User Inputs solely for the purposes of:
            </p>
            <ul>
              <li>Providing the Services to you (transmitting content to AI providers for processing)</li>
              <li>Temporarily storing generated content on our servers for up to 7 days</li>
              <li>Complying with legal obligations</li>
            </ul>
            <p>
              We do NOT use your User Inputs or Outputs to train our own AI models. However, third-party AI providers may use data in accordance with their own terms and policies.
            </p>

            <h3>5.3 Our Intellectual Property</h3>
            <p>
              The Services, including all software, user interface design, graphics, trademarks, logos, and documentation, are owned by or licensed to us and are protected by intellectual property laws. Nothing in these Terms grants you any right, title, or interest in our intellectual property except the limited right to use the Services as expressly permitted.
            </p>
          </section>

          <section>
            <h2>6. Prohibited Uses</h2>
            <p>You agree not to use the Services to:</p>
            <ul>
              <li>Generate content that is illegal under any applicable law</li>
              <li>Create child sexual abuse material (CSAM) or any content that sexually exploits or endangers minors</li>
              <li>Generate realistic deepfake videos of real, identifiable persons without their explicit written consent</li>
              <li>Create content intended to harass, threaten, bully, or intimidate any person</li>
              <li>Generate content that infringes upon any third party&rsquo;s intellectual property rights (copyrights, trademarks, etc.)</li>
              <li>Create misinformation or disinformation intended to deceive the public</li>
              <li>Impersonate any person or entity through generated content</li>
              <li>Attempt to reverse engineer, decompile, or disassemble any part of the Services or underlying AI models</li>
              <li>Circumvent, manipulate, or exploit the credit system (including abusing bugs, glitches, or errors)</li>
              <li>Use automated tools (bots, scripts) to access the Services</li>
              <li>Overwhelm or attempt to overwhelm our infrastructure</li>
              <li>Resell, redistribute, or sublicense access to the Services or generated content at scale without authorization</li>
              <li>Use the Services for any purpose that violates the terms of our AI providers (OpenAI, Google, xAI)</li>
            </ul>
            <p>
              We reserve the right to investigate and take action against violations at our sole discretion, including content removal, account suspension/termination, and reporting to law enforcement.
            </p>
          </section>

          <section>
            <h2>7. Content Moderation</h2>
            <p>
              Our AI providers employ content moderation systems that may refuse to generate certain content. Additionally, we may implement our own content filtering. We reserve the right to:
            </p>
            <ul>
              <li>Refuse to process any prompt that violates these Terms or our providers&rsquo; policies</li>
              <li>Remove generated content that violates these Terms</li>
              <li>Suspend or terminate accounts that repeatedly violate content policies</li>
              <li>Report illegal content to appropriate law enforcement authorities</li>
            </ul>
            <p>
              Credits consumed on generation attempts that are blocked by content moderation will be refunded to your account.
            </p>
          </section>

          <section>
            <h2>8. Generated Content — No Guarantees</h2>
            <p>
              AI-generated content is produced by third-party machine learning models. We make no representations or warranties regarding:
            </p>
            <ul>
              <li>The accuracy, quality, or suitability of any generated content</li>
              <li>Whether generated content is free from biases, errors, or objectionable material</li>
              <li>Whether generated content infringes any third-party intellectual property rights</li>
              <li>The continued availability of any specific AI provider or generation capability</li>
            </ul>
            <p>
              YOU ARE SOLELY RESPONSIBLE FOR REVIEWING ALL GENERATED CONTENT BEFORE USE AND FOR ENSURING THAT YOUR USE OF GENERATED CONTENT COMPLIES WITH ALL APPLICABLE LAWS.
            </p>
          </section>

          <section>
            <h2>9. Disclaimers</h2>
            <p>
              THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p>
              WITHOUT LIMITING THE FOREGOING, WE EXPRESSLY DISCLAIM ANY WARRANTY THAT:
            </p>
            <ul>
              <li>THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE</li>
              <li>THE RESULTS OBTAINED FROM THE SERVICES WILL BE ACCURATE OR RELIABLE</li>
              <li>THE QUALITY OF GENERATED CONTENT WILL MEET YOUR EXPECTATIONS</li>
              <li>ANY ERRORS WILL BE CORRECTED</li>
              <li>THE SERVICES WILL BE COMPATIBLE WITH ANY SPECIFIC DEVICE OR OS VERSION</li>
              <li>GENERATED CONTENT WILL NOT INFRINGE THIRD-PARTY RIGHTS</li>
              <li>THIRD-PARTY AI PROVIDERS WILL REMAIN AVAILABLE OR PERFORM CONSISTENTLY</li>
            </ul>
            <p>
              YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. WE ARE NOT RESPONSIBLE FOR THE ACTIONS, POLICIES, OR OUTPUT QUALITY OF THIRD-PARTY AI PROVIDERS (OPENAI, GOOGLE, XAI).
            </p>
          </section>

          <section>
            <h2>10. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AI VIDEO PLATFORM, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO:
            </p>
            <ul>
              <li>LOSS OF PROFITS, REVENUE, OR BUSINESS OPPORTUNITIES</li>
              <li>LOSS OF DATA, CONTENT, OR GENERATED VIDEOS</li>
              <li>LOSS OF CREDITS OR SUBSCRIPTION VALUE</li>
              <li>COST OF PROCUREMENT OF SUBSTITUTE SERVICES</li>
              <li>DAMAGE TO REPUTATION ARISING FROM AI-GENERATED CONTENT</li>
              <li>ANY DAMAGES ARISING FROM THIRD-PARTY AI PROVIDER ACTIONS OR FAILURES</li>
            </ul>
            <p>
              IN NO EVENT SHALL OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES EXCEED THE GREATER OF (A) ONE HUNDRED U.S. DOLLARS (US $100.00) OR (B) THE TOTAL AMOUNT PAID BY YOU TO US THROUGH IN-APP PURCHASES IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH LIABILITY.
            </p>
            <p>
              THESE LIMITATIONS APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>
              SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES. IN SUCH JURISDICTIONS, OUR LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW.
            </p>
          </section>

          <section>
            <h2>11. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless AI Video Platform from and against any and all claims, damages, obligations, losses, liabilities, costs, and expenses (including reasonable attorney&rsquo;s fees) arising from:
            </p>
            <ul>
              <li>Your use of the Services and any generated content</li>
              <li>Your User Inputs (prompts and uploaded images)</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights (including intellectual property rights)</li>
              <li>Your distribution or use of AI-generated content in a manner that causes harm</li>
              <li>Any claim that content you generated caused damage to a third party</li>
            </ul>
            <p>
              This indemnification obligation survives termination of these Terms.
            </p>
          </section>

          <section>
            <h2>12. Dispute Resolution and Arbitration</h2>

            <h3>12.1 Informal Resolution</h3>
            <p>
              Before initiating any formal legal proceedings, you agree to first attempt to resolve any dispute informally by contacting us at admin@aivideoplatform.ai. We will attempt to resolve the dispute within 60 days.
            </p>

            <h3>12.2 Binding Arbitration</h3>
            <p>
              If not resolved informally, any dispute shall be resolved exclusively through final and binding individual arbitration under the rules of the American Arbitration Association (AAA). The arbitration shall be conducted in English in the State of California, United States. The arbitrator&rsquo;s decision shall be final and binding.
            </p>

            <h3>12.3 Class Action Waiver</h3>
            <p>
              YOU AND AI VIDEO PLATFORM AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING.
            </p>

            <h3>12.4 Opt-Out</h3>
            <p>
              You may opt out of binding arbitration by sending written notice to admin@aivideoplatform.ai within 30 days of first using the Services. Your notice must include your anonymous UID and a clear statement that you wish to opt out.
            </p>

            <h3>12.5 Exceptions</h3>
            <p>
              Either party may bring claims in small claims court or seek injunctive relief for intellectual property infringement in any court of competent jurisdiction.
            </p>
          </section>

          <section>
            <h2>13. Apple App Store Additional Terms</h2>
            <p>
              The following terms apply to the extent the App is accessed through the Apple App Store:
            </p>
            <ul>
              <li>These Terms are between you and AI Video Platform only, and not with Apple Inc. (&ldquo;Apple&rdquo;). Apple is not responsible for the App or its content.</li>
              <li>Apple has no obligation to furnish any maintenance and support services with respect to the App.</li>
              <li>In the event of any failure of the App to conform to any applicable warranty, you may notify Apple for a refund of the purchase price (if applicable). Apple has no other warranty obligation with respect to the App.</li>
              <li>Apple is not responsible for addressing any claims relating to the App, including product liability claims, regulatory compliance claims, or intellectual property infringement claims.</li>
              <li>Apple and its subsidiaries are third-party beneficiaries of these Terms. Upon your acceptance, Apple will have the right to enforce these Terms against you as a third-party beneficiary.</li>
            </ul>
          </section>

          <section>
            <h2>14. Termination</h2>
            <p>
              We may suspend or terminate your access to the Services immediately, without prior notice, for any reason, including violation of these Terms.
            </p>
            <p>Upon termination:</p>
            <ul>
              <li>Your right to use the Services ceases immediately</li>
              <li>All remaining credits (subscription and one-time purchased) are forfeited</li>
              <li>Generated content stored on our servers will be deleted</li>
              <li>No refund will be provided for remaining subscription time or unused credits</li>
            </ul>
            <p>
              You may stop using the Services at any time by uninstalling the App. You may cancel active subscriptions through iOS Settings. All provisions that should survive termination will survive, including intellectual property, disclaimers, limitations of liability, indemnification, and dispute resolution.
            </p>
          </section>

          <section>
            <h2>15. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to conflict of law provisions. To the extent arbitration does not apply, you consent to the exclusive jurisdiction of courts located in California.
            </p>
          </section>

          <section>
            <h2>16. General Provisions</h2>

            <h3>16.1 Entire Agreement</h3>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and AI Video Platform regarding the Services.
            </p>

            <h3>16.2 Severability</h3>
            <p>
              If any provision is held invalid or unenforceable, it shall be modified to the minimum extent necessary or severed, and the remaining provisions continue in full force.
            </p>

            <h3>16.3 No Waiver</h3>
            <p>
              Our failure to enforce any right or provision shall not constitute a waiver of that right or provision.
            </p>

            <h3>16.4 Assignment</h3>
            <p>
              You may not assign these Terms. We may assign our rights and obligations without restriction.
            </p>

            <h3>16.5 Force Majeure</h3>
            <p>
              We are not liable for failures or delays caused by events beyond our reasonable control, including natural disasters, pandemics, government actions, internet failures, or third-party AI provider outages.
            </p>

            <h3>16.6 Modifications to Terms</h3>
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated via in-app notice. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2>17. Contact Us</h2>
            <p>If you have questions about these Terms of Use, please contact us at:</p>
            <p>
              AI Video Platform<br />
              Email: <a href="mailto:admin@aivideoplatform.ai" className="text-brand-500 hover:underline">admin@aivideoplatform.ai</a>
            </p>
          </section>

        </div>
      </div>
    </main>
  )
}
